#!/bin/sh

unset GIT_DIR

DeployPath="../local"

{
    cd $DeployPath
} || {
    echo "Error, Server update fail!"
    exit 1
}

{
    git reset --hard origin/master
    git clean -f
    git pull origin master
} || {
    echo "Error, Server update fail!"
    exit 1
}

echo "Server update done."
exit 0
