#!/bin/sh

unset GIT_DIR

MESSAGE=$(git log -1 HEAD --pretty=format:%s)
PRO="=>pro"
DepositoryPath=$PWD
DeployPathDev="../remote-dev"
DeployPathPro="../remote-pro"

if [[ "$MESSAGE" == *"$PRO"* ]]; then
    DeployPro=true
    echo "╔═══════════════════════════════════════╗"
    echo "║ Deploy to the production environment. ║"
    echo "╚═══════════════════════════════════════╝"
else
    DeployPro=false
    echo "╔════════════════════════════════════════╗"
    echo "║ Deploy to the development environment. ║"
    echo "╚════════════════════════════════════════╝"
fi

if $DeployPro; then

{
    cd $DeployPathPro
} || {
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║ Error, The production environment deployment path was not found! ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    exit 1
}

{
    git reset --hard origin/master
    git clean -f
    git pull origin master
    cd $DepositoryPath
} || {
    echo "╔══════════════════════════════════════════════════╗"
    echo "║ Error, Production environment deployment failed! ║"
    echo "╚══════════════════════════════════════════════════╝"
    exit 1
}

echo "╔═════════════════════════════════════════════════╗"
echo "║ Production environment deployment successfully. ║"
echo "╚═════════════════════════════════════════════════╝"

fi

{
    cd $DeployPathDev
} || {
    echo "╔═══════════════════════════════════════════════════════════════════╗"
    echo "║ Error, The development environment deployment path was not found! ║"
    echo "╚═══════════════════════════════════════════════════════════════════╝"
    exit 1
}

{
    git reset --hard origin/master
    git clean -f
    git pull origin master
} || {
    echo "╔═══════════════════════════════════════════════════╗"
    echo "║ Error, Development environment deployment failed! ║"
    echo "╚═══════════════════════════════════════════════════╝"
    exit 1
}

echo "╔══════════════════════════════════════════════════╗"
echo "║ Development environment deployment successfully. ║"
echo "╚══════════════════════════════════════════════════╝"

exit 0
