#!/bin/sh

unset GIT_DIR

MESSAGE=$(git log -1 HEAD --pretty=format:%s)
PRO="=>pro"
DepositoryPath=$PWD
DeployPathDev="../remote-dev"
DeployPathPro="../remote-pro"

if [[ "$MESSAGE" == *"$PRO"* ]]; then
    DeployPro=true
    echo "Deploy to the production environment."
else
    DeployPro=false
    echo "Deploy to the development environment."
fi

if $DeployPro; then

{
    cd $DeployPathPro
} || {
    echo "Error, The production environment deployment path was not found!"
    exit 1
}

{
    git reset --hard origin/master
    git clean -f
    git pull origin master
    cd $DepositoryPath
} || {
    echo "Error, Production environment deployment failed!"
    exit 1
}

echo "Production environment deployment successfully."

fi

{
    cd $DeployPathDev
} || {
    echo "Error, The development environment deployment path was not found!"
    exit 1
}

{
    git reset --hard origin/master
    git clean -f
    git pull origin master
} || {
    echo "Error, Development environment deployment failed!"
    exit 1
}

echo "Development environment deployment successfully."

exit 0
